-- SQLite
SELECT TEMPERATURA_AMBIENTE, TIPO_ISOLACAO, TIPO_EXPOSICAO, FATOR_CORRECAO_TEMP

FROM TB_FATOR_CORRECAO_TEMP;



alter table  
 TB_FATOR_CORRECAO_TEMP
 add temp_isolacao int;


update TB_FATOR_CORRECAO_TEMP set temp_isolacao = 105 where TIPO_ISOLACAO like '%105%'