

INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 1	,'Três cabos unipolares afastados em "De"','','e = De',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 2	,'Três cabos unipolares afastados em "2.De"','','e = 2.De',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 3	,'Três cabos unipolares em trifólio','','e = 0',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 4	,'Dois grupos formados por cabos unipolares em trifólio, na horizontal','','e ≥ De',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 5	,'Dois grupos formados por cabos unipolares em trifólio, na horizontal','','e < De',0.93;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 6	,'Três grupos formados por cabos unipolares em trifólio, na horizontal','','e ≥ 1,5·De ',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 7	,'Três grupos formados por cabos unipolares em trifólio, na horizontal','','e < 1,5·De',0.92;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 8	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','e ≥ 3,5·De ',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 9	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','2,5·De ≤ e < 3,5·De ',0.99;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 10	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','2·De ≤ e < 2,5·De ',0.98;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 11	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','1,5·De ≤ e < 2·De',0.97;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 12	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','De ≤ e < 1,5·De ',0.96;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 13	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','0,5·De ≤ e < De',0.94;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 14	,'Dois grupos formados por cabos unipolares em trifólio, na vertical','','e < 0,5·De',0.88;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 15	,'Dois conjuntos de grupos com dois trifólios na vertical','','e ≥ 3,5·De',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 16	,'Dois conjuntos de grupos com dois trifólios na vertical','','2,5·De ≤ e < 3,5·De',0.99;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 17	,'Dois conjuntos de grupos com dois trifólios na vertical','','2·De ≤ e < 2,5·De',0.98;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 18	,'Dois conjuntos de grupos com dois trifólios na vertical','','1,5·De ≤ e < 2·De',0.97;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 19	,'Dois conjuntos de grupos com dois trifólios na vertical','','De ≤ e < 1,5·De',0.96;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 20	,'Dois conjuntos de grupos com dois trifólios na vertical','','0,5·De ≤ e < De',0.94;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 21	,'Dois conjuntos de grupos com dois trifólios na vertical','','e < 0,5·De',0.88;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 22	,'Três conjuntos de grupos com dois trifólios na vertical','','e ≥ 3,5·De',1.00;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 23	,'Três conjuntos de grupos com dois trifólios na vertical','','2,5·De ≤ e < 3,5·De',0.99;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 24	,'Três conjuntos de grupos com dois trifólios na vertical','','2·De ≤ e < 2,5·De',0.98;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 25	,'Três conjuntos de grupos com dois trifólios na vertical','','1,5·De ≤ e < 2·De',0.97;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 26	,'Três conjuntos de grupos com dois trifólios na vertical','','De ≤ e < 1,5·De',0.96;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 27	,'Três conjuntos de grupos com dois trifólios na vertical','','0,5·De ≤ e < De',0.94;   
INSERT INTO TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 SELECT 28	,'Três conjuntos de grupos com dois trifólios na vertical','','e < 0,5·De',0.88;   


INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	1	, 'Um cabo tripolar na horizontal', '', 'e =0', 							1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	2	, 'Dois cabos tripolares na horizontal', '', 'e ≥ 0,5·De',  					1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	3	, 'Dois cabos tripolares na horizontal', '', 'e < 0,5·De',  					0.89;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	4	, 'Três cabos tripolares na horizontal', '', 'e ≥ 0,75·De', 					1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	5	, 'Três cabos tripolares na horizontal', '', 'e < 0,75·De', 					0.84;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	6	, 'Dois cabos tripolares na vertical', '', 'e ≥ 2·De', 						1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	7	, 'Dois cabos tripolares na vertical', '', '1,5·De ≤ e < 2·De', 					0.99;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	8	, 'Dois cabos tripolares na vertical', '', 'De ≤ e < 1,5·De', 					0.97;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	9	, 'Dois cabos tripolares na vertical', '', '0,5·De ≤ e < De', 					0.94;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	10	, 'Dois cabos tripolares na vertical', '', 'e < 0,5·De',						0.90;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	11	, 'Três cabos tripolares na vertical', '', 'e ≥ 3,5·De',						1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	12	, 'Três cabos tripolares na vertical', '', '3·De ≤ e < 3,5·De', 					0.99;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	13	, 'Três cabos tripolares na vertical', '', '2,5·De ≤ e < 3·De', 					0.98;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	14	, 'Três cabos tripolares na vertical', '', '2·De ≤ e < 2,5·De', 					0.97;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	15	, 'Três cabos tripolares na vertical', '', '1,5·De ≤ e < 2·De', 					0.96;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	16	, 'Três cabos tripolares na vertical', '', 'De ≤ e < 1,5·De', 					0.94;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	17	, 'Três cabos tripolares na vertical', '', '0,5·De ≤ e < De', 					0.91;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	18	, 'Três cabos tripolares na vertical', '', 'e < 0,5·De', 						0.85;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	19	, 'Dois conjuntos de grupos com dois cabos tripolares na vertical', '', 'e ≥ 2·De', 		1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	20	, 'Dois conjuntos de grupos com dois cabos tripolares na vertical', '', '1,5·De ≤ e < 2·De',	0.99;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	21	, 'Dois conjuntos de grupos com dois cabos tripolares na vertical', '', 'De ≤ e < 1,5·De',		0.97;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	22	, 'Dois conjuntos de grupos com dois cabos tripolares na vertical', '', '0,5·De ≤ e < De', 		0.94;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	23	, 'Dois conjuntos de grupos com dois cabos tripolares na vertical', '', 'e < 0,5·De', 		0.90;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	24	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', 'e ≥ 3,5·De', 		1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	25	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', '3·De ≤ e < 3,5·De', 	0.99;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	26	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', '2,5·De ≤ e < 3·De', 	0.98;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	27	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', '2·De ≤ e < 2,5·De', 	0.97;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	28	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', '1,5·De ≤ e < 2·De', 	0.96;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	29	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', 'De ≤ e < 1,5·De',	 	0.94;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	30	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', '0,5·De ≤ e < De', 		0.91;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	31	, 'Dois conjuntos de grupos com três cabos tripolares na vertical', '', 'e < 0,5·De', 		0.85;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	32	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', 'e ≥ 3,5·De', 		1.00;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	33	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', '3·De ≤ e < 3,5·De', 	0.99;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	34	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', '2,5·De ≤ e < 3·De', 	0.98;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	35	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', '2·De ≤ e < 2,5·De',	0.97;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	36	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', '1,5·De ≤ e < 2·De', 	0.96;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	37	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', 'De ≤ e < 1,5·De', 		0.94;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	38	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', '0,5·De ≤ e < De', 		0.91;
INSERT INTO TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 SELECT	39	, 'Três conjuntos de grupos com três cabos tripolares na vertical', '', 'e < 0,5·De', 		0.85;

