-- SQLite

CREATE TABLE TABELA_25_TIPOS_LINHAS(


[id_metodo] VARCHAR(200),
[Método de referência resumido] VARCHAR(200),
[Método de referência (simplificado)] VARCHAR(200),
[Método de referência (Código)] VARCHAR(200),
[Tabelade referência - correção por temperatura] VARCHAR(200),
[unipolares] VARCHAR(200),
[tripolar] VARCHAR(200),
[tripolares] VARCHAR(200),
[qtd cabo = 1] VARCHAR(200),
[qtd cabo > 1] VARCHAR(200));



INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '1A1' , 'A1 - Cabos ao ar livre, em bandeja perfurada, protegido do sol' , 'Ao ar livre' , 'A1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em bandeja perfurada, protegido do sol' , 'em bandeja perfurada, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '2A2' , 'A2 - Cabos ao ar livre, em bandeja perfurada, exposto do sol' , 'Ao ar livre' , 'A2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em bandeja perfurada, exposto do sol' , 'em bandeja perfurada, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '3B1' , 'B1 - Cabos ao ar livre, em bandeja perfurada, protegido do sol' , 'Ao ar livre' , 'B1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em bandeja perfurada, protegido do sol' , 'em bandeja perfurada, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '4B2' , 'B2 - Cabos ao ar livre, em bandeja perfurada, exposto do sol' , 'Ao ar livre' , 'B2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em bandeja perfurada, exposto do sol' , 'em bandeja perfurada, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '5A1' , 'A1 - Cabos ao ar livre, em eletrocalha aramada, protegido do sol' , 'Ao ar livre' , 'A1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletrocalha aramada, protegido do sol' , 'em eletrocalha aramada, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '6A2' , 'A2 - Cabos ao ar livre, em eletrocalha aramada, exposto do sol' , 'Ao ar livre' , 'A2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletrocalha aramada, exposto do sol' , 'em eletrocalha aramada, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '7B1' , 'B1 - Cabos ao ar livre, em eletrocalha aramada, protegido do sol' , 'Ao ar livre' , 'B1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletrocalha aramada, protegido do sol' , 'em eletrocalha aramada, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '8B2' , 'B2 - Cabos ao ar livre, em eletrocalha aramada, exposto do sol' , 'Ao ar livre' , 'B2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletrocalha aramada, exposto do sol' , 'em eletrocalha aramada, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '2A1' , 'A1 - Cabos ao ar livre, em leito, protegido do sol' , 'Ao ar livre' , 'A1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em leito, protegido do sol' , 'em leito, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '3A2' , 'A2 - Cabos ao ar livre, em leito, exposto do sol' , 'Ao ar livre' , 'A2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em leito, exposto do sol' , 'em leito, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '4B1' , 'B1 - Cabos ao ar livre, em leito, protegido do sol' , 'Ao ar livre' , 'B1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em leito, protegido do sol' , 'em leito, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '5B2' , 'B2 - Cabos ao ar livre, em leito, exposto do sol' , 'Ao ar livre' , 'B2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em leito, exposto do sol' , 'em leito, exposto do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '6A1' , 'A1 - Cabo multiplexado, autossustentado, ao ar livre, protegido do sol' , 'Ao ar livre' , 'A1' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo multiplexado' , 'cabos multiplexados' , 'ao ar livre, protegido do sol' , 'Cabo multiplexado ao ar livre, protegido do sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '7A2' , 'A2 - Cabo multiplexado, autossustentado, ao ar livre, exposto ao sol' , 'Ao ar livre' , 'A2' , 'Fator de correção temperatura (Tabela 30 - NBR:14039):' , 'cabos unipolares' , 'cabo multiplexado' , 'cabos multiplexados' , 'ao ar livre, exposto ao sol' , 'Cabo multiplexado ao ar livre, exposto ao sol';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '8' , 'C - Cabos em canaletas fechadas no solo' , 'Em canaletas' , 'C' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em canaletas fechadas no solo' , 'em canaletas fechadas no solo';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '9' , 'D - Cabos unipolares espaçados em canaletas fechadas no solo' , 'Em canaletas' , 'D' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em canaletas fechadas no solo' , 'em canaletas fechadas no solo';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '10' , 'E - Cabos unipolares na horizontal ou em trifólio em eletroduto ao ar livre' , 'Em eletroduto ao ar livre' , 'E' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto ao ar livre' , 'em eletrodutos ao ar livre';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '11' , 'E - Cabos tripolares em eletroduto ao ar livre' , 'Em eletroduto ao ar livre' , 'E' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto ao ar livre' , 'em eletrodutos ao ar livre';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '12' , 'F1 - Cabos unipolares em eletroduto diretamente enterrado' , 'Em canaletas' , 'F1' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto diretamente enterrado' , 'em eletrodutos diretamente enterrado';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '13' , 'F1 - Cabos tripolares em eletroduto diretamente enterrado' , 'Em eletroduto enterrado' , 'F1' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto diretamente enterrado' , 'em eletrodutos diretamente enterrado';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '14' , 'F2 - Cabos unipolares em eletroduto embutido em concreto e enterrado no solo' , 'Em banco de dutos' , 'F2' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto embutido em concreto e enterrado no solo' , 'em eletrodutos embutidos em concreto e enterrado no solo';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '15' , 'F2 - Cabos tripolares em eletroduto embutido em concreto e enterrado no solo' , 'Em banco de dutos' , 'F2' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletroduto embutido em concreto e enterrado no solo' , 'em eletrodutos embutidos em concreto e enterrado no solo';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '16' , 'G1 - Cabos unipolares em eletrodutos enterrados e espaçados – um cabo por eletroduto não condutor' , 'Em banco de dutos' , 'G1' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em eletrodutos enterrados e espaçados – um cabo por eletroduto' , 'em eletrodutos enterrados e espaçados – um cabo por eletroduto';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '17' , 'G2 - Cabos unipolares em banco de dutos enterrado – um cabo por eletroduto não condutor' , 'Em banco de dutos' , 'G2' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em banco de dutos enterrado – um cabo por eletroduto não condutor' , 'em banco de dutos enterrado – um cabo por eletroduto não condutor';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '18' , 'H - Cabos unipolares em formação plana e em contato diretamente enterrados' , 'Diretamente enterrados' , 'H' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em formação plana e em contato diretamente enterrados' , 'em formação plana e em contato diretamente enterrados';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '19' , 'H - Cabos unipolares em formação trifólio diretamente enterrados' , 'Diretamente enterrados' , 'H' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'em formação trifólio diretamente enterrados' , 'em formação trifólio diretamente enterrados';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '20' , 'H - Cabo tripolar diretamente enterrado' , 'Diretamente enterrados' , 'H' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'diretamente enterrado' , 'diretamente enterrados';
INSERT INTO TABELA_25_TIPOS_LINHAS SELECT '21' , 'I - Cabos unipolares espaçados, diretamente enterrados' , 'Diretamente enterrados' , 'I' , 'Fator de correção temperatura (Tabela 31 - NBR:14039):' , 'cabos unipolares' , 'cabo tripolar' , 'cabos tripolares' , 'espaçados, diretamente enterrados' , 'espaçados, diretamente enterrados';

