
create table TB_FATOR_CORRECAO_TEMP (
TEMPERATURA_AMBIENTE INTEGER,
TIPO_ISOLACAO VARCHAR (100),
TIPO_EXPOSICAO VARCHAR (100),
FATOR_CORRECAO_TEMP FLOAT
);


INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 10 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol', 1.15;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',1.12;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',1.08;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',1.04;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',1.00;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.96;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.91;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.87;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.82;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.76;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.71;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 65 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.65;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 70 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.58;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 75 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.5;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 80 ,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Abrigada do sol',0.41;

INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 10 ,'Isolação de EPR 105ºC',   'Abrigada do sol', 1.13; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15 ,'Isolação de EPR 105ºC',   'Abrigada do sol', 1.10; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20 ,'Isolação de EPR 105ºC',   'Abrigada do sol',1.06; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25 ,'Isolação de EPR 105ºC',   'Abrigada do sol',1.03; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30 ,'Isolação de EPR 105ºC',   'Abrigada do sol',1.00; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.97; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.93; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.89; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.86; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.82; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.77; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 65 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.73; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 70 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.68; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 75 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.63; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 80 ,'Isolação de EPR 105ºC',   'Abrigada do sol',0.58; 

INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT  10,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 1.15; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 1.12; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 1.08; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 1.04; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 1.00; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.92; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.83; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.73; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.62; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.49; 
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC','Exposta ao sol', 0.31; 

INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT  10,'Isolação de EPR 105ºC', 'Exposta ao sol',1.13;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15,'Isolação de EPR 105ºC', 'Exposta ao sol',1.10;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20,'Isolação de EPR 105ºC', 'Exposta ao sol',1.06;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25,'Isolação de EPR 105ºC', 'Exposta ao sol',1.03;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30,'Isolação de EPR 105ºC', 'Exposta ao sol',1.00;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35,'Isolação de EPR 105ºC', 'Exposta ao sol',0.94;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40,'Isolação de EPR 105ºC', 'Exposta ao sol',0.88;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45,'Isolação de EPR 105ºC', 'Exposta ao sol',0.82;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50,'Isolação de EPR 105ºC', 'Exposta ao sol',0.75;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55,'Isolação de EPR 105ºC', 'Exposta ao sol',0.68;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60,'Isolação de EPR 105ºC', 'Exposta ao sol',0.60;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 65,'Isolação de EPR 105ºC', 'Exposta ao sol',0.51;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 70,'Isolação de EPR 105ºC', 'Exposta ao sol',0.40;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 75,'Isolação de EPR 105ºC', 'Exposta ao sol',0.25;

INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT  10,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 1.07;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 1.04;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 1.00;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.96;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.93;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.89;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.85;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.80;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.76;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.71;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.65;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 65,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.60;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 70,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.53;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 75,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.46;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 80,'Isolação de EPR, HEPR, XLPE ou TR XLPE 90ºC', 'subterrâneas', 0.38;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT  10,'Isolação de EPR 105ºC',     'subterrâneas', 1.06;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 15,'Isolação de EPR 105ºC',     'subterrâneas', 1.03;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 20,'Isolação de EPR 105ºC',     'subterrâneas', 1.00;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 25,'Isolação de EPR 105ºC',    'subterrâneas', 0.97;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 30,'Isolação de EPR 105ºC',    'subterrâneas', 0.94;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 35,'Isolação de EPR 105ºC',    'subterrâneas', 0.91;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 40,'Isolação de EPR 105ºC',    'subterrâneas', 0.87;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 45,'Isolação de EPR 105ºC',    'subterrâneas', 0.84;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 50,'Isolação de EPR 105ºC',    'subterrâneas', 0.80;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 55,'Isolação de EPR 105ºC',    'subterrâneas', 0.77;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 60,'Isolação de EPR 105ºC',    'subterrâneas', 0.73;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 65,'Isolação de EPR 105ºC',    'subterrâneas', 0.69;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 70,'Isolação de EPR 105ºC',    'subterrâneas', 0.64;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 75,'Isolação de EPR 105ºC',    'subterrâneas', 0.59;
INSERT INTO TB_FATOR_CORRECAO_TEMP SELECT 80,'Isolação de EPR 105ºC',    'subterrâneas', 0.54;
