-- SQLite


create table TABELA_34_FATORES_CORRECAO_CABOS_UNIPOLARES_REF_A1 (
ID INTEGER,
GRUPO VARCHAR(200),
ESQUEMA_ILUSTRATIVO VARCHAR(500),
ESPACAMENTO_A_B VARCHAR(100),
FATOR_CORRECAO FLOAT     
);



create table TABELA_35_FATORES_CORRECAO_CABOS_TRIPOLARES_REF_A1 (
ID INTEGER,
GRUPO VARCHAR(200),
ESQUEMA_ILUSTRATIVO VARCHAR(500),
ESPACAMENTO_A_B VARCHAR(100),
FATOR_CORRECAO FLOAT     
) ;
